name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set PSRepository to Trusted for PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      - name: Install PScribo module
        shell: pwsh
        run: |
          Install-Module -Name PScribo -Repository PSGallery -Force
      - name: Install Brickset module
        shell: pwsh
        run: |
          Install-Module -Name Brickset -Repository PSGallery -Force
      - name: Test Module Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\BricksetCatalogue.psd1
      - name: Publish module to PowerShell Gallery
        shell: pwsh
        run: |
          Publish-Module -Path ./ -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }} -Verbose
